
language: python
python:
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install cython
  - pip install -e .
  - pip install coverage
  - pip install numpy
  - pip install soundfile

script:
  - pytest tests/

